// GameContent — the prompt library behind Game Night. Every game has a FREE
// pool and a SPICY pool; a round deals `roundSize` random cards from the
// chosen pool, so the same table can play night after night without
// recognising the deck. Pandora cards carry a category prefix
// ("DARE — …", "RULE — …", "TRUTH — …", "CHALLENGE — …") that the card UI
// turns into a badge.

import Foundation

enum GameContent {
    /// Cards per round — long enough for a proper session, short enough
    /// that the end-of-round "step it up" prompt actually gets seen.
    static let roundSize = 40

    static func pool(for kind: GameKind, spicy: Bool) -> [String] {
        switch (kind, spicy) {
        case (.imposter, false):   return imposterFree
        case (.imposter, true):    return imposterSpicy
        case (.never, false):      return neverFree
        case (.never, true):       return neverSpicy
        case (.pandora, false):    return pandoraFree
        case (.pandora, true):     return pandoraSpicy
        case (.mostLikely, false): return mostLikelyFree
        case (.mostLikely, true):  return mostLikelySpicy
        }
    }

    /// Free rounds are half-length; After Dark plays the full 40.
    static let freeRoundSize = 20

    /// A fresh round: `count` cards, no repeats, random order.
    static func deal(for kind: GameKind, spicy: Bool, count: Int = roundSize) -> [String] {
        Array(pool(for: kind, spicy: spicy).shuffled().prefix(count))
    }

    // MARK: - Imposter — secret words

    static let imposterFree: [String] = [
        "Karaoke", "Tequila", "Afterparty", "Beer pong", "Hangover", "Kebab", "Dance floor",
        "Shots", "Pre-drink", "Bouncer", "Taxi", "Wingman", "Last call", "Happy hour", "Bartender",
        "Festival", "Nightclub", "Rooftop bar", "Pub crawl", "DJ", "Champagne", "Beach party",
        "House party", "Jägerbomb", "Cider", "Espresso martini", "Dive bar", "VIP table",
        "Dance battle", "Toast", "Ice bucket", "Cocktail", "Snapchat", "Group chat", "Selfie",
        "Vegas", "Ibiza", "Cruise", "Sauna", "Midsummer", "Crayfish party", "Studentflak",
        "Valborg", "Systembolaget", "Falukorv", "IKEA", "Eurovision", "ABBA", "Coat check",
        "Guest list", "Open bar", "Bottle service", "Aux cable", "Uber", "Night bus", "Gym",
        "Tinder", "Netflix", "Spotify", "Hot dog", "Pizza", "Sushi", "Taco Tuesday", "Brunch",
        "Coffee", "Energy drink", "Water", "Aspirin", "Sunglasses", "Umbrella", "Passport",
        "Airport", "Hotel", "Hostel", "Camping", "Bonfire", "Fireworks", "New Year's Eve",
        "Birthday", "Wedding", "Bachelor party", "Graduation", "First date", "Blind date",
        "Roommate", "Landlord", "Wi-Fi", "Password", "Charger", "Headphones", "Podcast",
        "TikTok", "Instagram", "Influencer", "Meme", "Emoji", "Voice message", "Screenshot",
        "Read receipt", "Group project", "Exam", "Deadline", "Coffee break", "Lunch", "Boss",
        "Office party", "Zoom", "Monday", "Friday", "Weekend", "Payday", "Rent", "Discount",
        "Black Friday", "Shopping", "Sneakers", "Hoodie", "Tattoo", "Piercing", "Haircut",
        "Beard", "Perfume", "Mirror", "Gym selfie", "Protein shake", "Yoga", "Marathon",
        "Football", "Hockey", "Ski trip", "Snowboard", "Surfing", "Skateboard", "Bicycle",
        "Electric scooter", "Traffic jam", "Parking ticket", "Speed camera", "Ferry",
        "Train", "Metro", "Delay", "Lost luggage", "Jet lag", "Sunburn", "Mosquito",
        "Tent", "Barbecue", "Picnic", "Lake", "Archipelago", "Sailing", "Fishing",
        "Moose", "Reindeer", "Northern lights", "Snowman", "Ice hotel", "Fika", "Cinnamon bun",
        "Meatballs", "Herring", "Surströmming", "Kanelbulle", "Semla", "Glögg", "Julbord",
        "Lucia", "Easter egg", "Halloween", "Costume", "Pumpkin", "Vampire", "Zombie",
        "Superhero", "Villain", "Plot twist", "Sequel", "Cliffhanger", "Spoiler", "Trailer",
        "Popcorn", "Cinema", "Theatre", "Concert", "Encore", "Mosh pit", "Front row",
        "Backstage", "Autograph", "Paparazzi", "Red carpet", "Award show", "Trophy",
        "Gold medal", "Olympics", "World Cup", "Penalty", "Referee", "Own goal", "Overtime",
        "Poker", "Bluff", "Jackpot", "Lottery", "Casino", "Roulette", "Dice", "Chess",
        "Monopoly", "Puzzle", "Crossword", "Sudoku", "Quiz night", "Karaoke duet",
        "Air guitar", "Drum solo", "Beatbox", "Rap battle", "Lip sync", "Slow dance",
        "Moonwalk", "Cartwheel", "Handstand", "Push-up", "Plank", "Sprint", "Sunrise",
        "Sunset", "Full moon", "Thunderstorm", "Rainbow", "Snow day", "Heatwave",
    ]

    static let imposterSpicy: [String] = [
        "One-night stand", "Walk of shame", "Friends with benefits", "Skinny dipping",
        "Body shot", "Strip poker", "Tinder date", "Sexting", "Love bite", "Hot tub",
        "Lap dance", "First kiss", "Situationship", "Ex", "Booty call", "Morning after",
        "Hotel room", "Truth or dare", "Seven minutes in heaven", "Crush", "Threesome",
        "Roleplay", "Sugar daddy", "Nudes", "Hickey", "Spooning", "Big spoon", "Little spoon",
        "Rebound", "Ghosting", "Breadcrumbing", "Love triangle", "Secret admirer",
        "Slow burn", "Bad boy", "Player", "Heartbreaker", "Soulmate", "Sugar baby",
        "Hall pass", "Open relationship", "Bedroom eyes", "Pickup line", "Cheesy line",
        "Flirting", "Wink", "Eye contact", "Slow dance", "Body language", "Lingerie",
        "Silk sheets", "Massage", "Candlelight", "Bubble bath", "Champagne in bed",
        "Room service", "Do not disturb", "Late checkout", "Honeymoon", "Airport kiss",
        "Kiss cam", "Mistletoe", "New Year's kiss", "Midnight swim", "Beach at night",
        "Rooftop at 3 AM", "After hours", "Private party", "Backseat", "Elevator",
        "Fitting room", "Office romance", "Teacher's pet", "Long-distance", "Sneaking out",
        "Sneaking in", "Sleepover", "Pillow talk", "Morning coffee", "Netflix and chill",
        "Kiss and tell", "Body count", "Dry spell", "Rizz", "Green flag", "Red flag",
        "Ick", "Type", "Situationship talk", "Define the relationship", "Dating app bio",
        "Super like", "Match", "Unmatch", "Left on read", "Late-night text", "Risky text",
        "Voice note at 2 AM", "Drunk dial", "Ex's number", "Old flame", "Summer fling",
        "Holiday romance", "Festival hookup", "Crush's best friend", "Forbidden fruit",
        "Guilty pleasure", "Wild side", "Poker face", "Blushing",
        "Bachelor party", "Bachelorette", "Stag do", "Hen night", "Speed dating", "Blind date",
        "Double date", "First base", "Home run", "Curveball", "Rain check", "Last kiss",
        "Goodbye kiss", "Cheek kiss", "French kiss", "Air kiss", "Kiss on the hand", "Forehead kiss",
        "Butterfly kiss", "Slow kiss", "Stolen kiss", "Dance floor kiss", "Taxi kiss", "Doorstep kiss",
        "Staircase kiss", "Kitchen kiss", "Jealousy", "Chemistry", "Tension", "Spark", "Butterflies",
        "Heartbeat", "Goosebumps", "Weak knees", "Cold feet", "Second thoughts", "Commitment",
        "Anniversary", "Valentine's", "Love letter", "Mixtape", "Playlist", "Handwritten note",
        "Secret", "Confession", "Alibi", "Cover story", "Wingwoman", "Third wheel", "Chaperone",
        "Curfew", "Hotel key", "Room 404", "Balcony", "Fire escape", "Jacuzzi", "Sauna date",
        "Beach towel", "Sunscreen", "Tan lines", "Bikini", "Swim trunks", "Speedo", "Boxers",
        "Pyjamas", "Robe", "Slippers", "Perfume on a shirt", "Borrowed hoodie", "Toothbrush",
        "Drawer space", "Spare key", "Meet the parents", "Moving in", "Ring", "Proposal",
        "Eloping", "Honeymoon suite", "Divorce party", "Ex's wedding", "Plus one", "Bouquet toss",
        "Garter", "First dance", "Open bar wedding", "Wedding crasher", "Drunk toast",
        "Sober kiss", "Tipsy confession", "Truth serum", "Dare card", "Spin the bottle",
        "Two truths and a lie", "Playing hard to get", "Making a move",
        "Missed connection", "Right person wrong time", "Almost relationship", "The one that got away",
    ]

    // MARK: - Never Have I Ever

    static let neverFree: [String] = [
        "…thrown up from drinking.", "…blacked out.", "…been kicked out of a bar.",
        "…cried at a party.", "…lied about how much I've drunk.", "…fallen asleep at a party.",
        "…texted an ex while drunk.", "…lost my phone on a night out.", "…danced on a table.",
        "…snuck into a club underage.", "…pretended to know a song at karaoke.",
        "…drunk-called my boss or a teacher.", "…eaten food off the floor.",
        "…been in a drinking competition.", "…mixed four kinds of alcohol in one night.",
        "…woken up in someone else's clothes.", "…forgotten where I left my bike.",
        "…been carried home.", "…started a sing-along on public transport.",
        "…lied to my parents about where I was.", "…ghosted the group chat the morning after.",
        "…ordered food for the table and eaten it all myself.",
        "…fake-laughed at a story I've heard five times.", "…left without saying goodbye.",
        "…napped in a bar bathroom.", "…borrowed money on a night out and never paid it back.",
        "…cried over a sports result.", "…been on TV.", "…stalked a profile back more than a year.",
        "…sent a message to the wrong group chat.", "…pretended my phone died to leave early.",
        "…lost a shoe on a night out.", "…hidden snacks from my friends.",
        "…slept through a whole day after partying.", "…been on a party bus.",
        "…jumped into water with my clothes on.", "…convinced a stranger we'd met before.",
        "…made the group miss the last train.", "…ugly-cried to a song everyone else danced to.",
        "…been the first one to fall asleep at a sleepover.", "…broken something at a party and hidden it.",
        "…gone to work or school with a hangover.", "…thrown a party while my parents were away.",
        "…been the last person on the dance floor.", "…had a full conversation with a stranger's dog.",
        "…lied about my age.", "…pretended to be a tourist to get out of something.",
        "…been on a first date and wanted to leave in five minutes.", "…fallen asleep in a taxi.",
        "…taken a taxi less than 500 metres.", "…cried in a taxi.", "…sung to a taxi driver.",
        "…been to a club alone.", "…gone to a concert of an artist I couldn't name a song by.",
        "…worn sunglasses indoors on purpose.", "…worn the same outfit two nights in a row.",
        "…lost a bet and actually paid.", "…won a bet and never collected.",
        "…had a nickname I hated stick for years.", "…pretended to be asleep to avoid talking.",
        "…faked being sick to skip plans.", "…double-booked myself on purpose.",
        "…said \"I'm five minutes away\" from my bed.", "…left a party to buy snacks and never came back.",
        "…eaten kebab for breakfast.", "…had pizza three days in a row.",
        "…ordered food at 4 AM.", "…forgotten someone's name mid-conversation.",
        "…called someone the wrong name.", "…waved at someone who wasn't waving at me.",
        "…walked into a glass door.", "…tripped in front of a crowd.",
        "…been asked to leave a store.", "…got lost in my own city.",
        "…taken the wrong train and ended up somewhere new.", "…missed a flight.",
        "…slept at an airport.", "…lost my passport.", "…been sunburnt on one side only.",
        "…gotten a tattoo on impulse.", "…cut my own hair and regretted it.",
        "…dyed my hair a colour I hated.", "…worn a costume in public when it wasn't a party.",
        "…kept a secret for more than five years.", "…told a secret I promised to keep.",
        "…read someone else's messages.", "…had my messages read by someone else.",
        "…cried in front of my boss.", "…quit something on the spot.",
        "…walked out of a movie.", "…fallen asleep in a cinema.",
        "…snored in public.", "…talked in my sleep and been told about it.",
        "…been on a game show or in a competition on stage.", "…been in a newspaper.",
        "…been recognised by a stranger.", "…met a celebrity and said something stupid.",
        "…had a celebrity follow me back.", "…gone viral, even a little.",
        "…deleted a post because it got no likes.", "…posted then un-posted a story within a minute.",
        "…liked a photo from years back by accident.", "…been caught screenshotting a story.",
        "…pretended not to see someone I know in public.", "…hidden from a neighbour.",
        "…used a fake name at a café.", "…sent a voice note longer than three minutes.",
        "…left someone on read for a week.", "…been left on read for a month.",
        "…replied to a message a year late.", "…had a group chat made without me.",
        "…made a group chat without someone.", "…muted this group chat.",
        "…been the reason a group chat went silent.", "…won an argument by being louder.",
        "…lost an argument and pretended I didn't.", "…googled someone before meeting them.",
        "…been googled and heard about it.", "…changed my order because someone judged it.",
        "…eaten something I dropped in front of everyone.", "…finished someone else's drink by accident.",
        "…finished someone else's drink on purpose.", "…been given a free drink by a bartender.",
        "…tipped way too much by accident.", "…paid for a whole round I didn't mean to.",
        "…had a tab I couldn't explain the next morning.", "…found receipts I didn't remember.",
        "…found a new contact in my phone I didn't remember.", "…woken up with a new friend on Instagram.",
        "…woken up with a bruise I couldn't explain.", "…lost a jacket on a night out.",
        "…gone home in someone else's jacket.", "…worn a bar's stamp for two days.",
        "…kept a wristband on for a week.", "…been to a festival without a ticket.",
        "…climbed something I shouldn't have.", "…gone swimming somewhere I shouldn't have.",
        "…run from a security guard.", "…hidden in a bathroom to avoid someone.",
        "…locked myself out.", "…locked someone else out by accident.",
        "…slept on a friend's floor.", "…slept in a bathtub.",
        "…ended up at a stranger's afterparty.", "…hosted an afterparty I didn't want.",
        "…been the last guest to leave.", "…been asked to leave a party.",
        "…thrown a party nobody came to.", "…gone to a party I wasn't invited to.",
        "…forgotten a friend's birthday.", "…had my birthday forgotten.",
        "…re-gifted a present.", "…received a re-gifted present and known.",
        "…cried at a wedding.", "…caught the bouquet.", "…given a toast that went badly.",
        "…fallen asleep at a wedding.", "…been dumped by text.", "…dumped someone by text.",
        "…had a relationship shorter than a week.", "…been in a long-distance relationship.",
        "…gone on a date just for the free meal.", "…been on a double date.",
        "…been set up by a friend.", "…set up two friends who hated it.",
        "…had a crush on a teacher.", "…had a crush on a friend's sibling.",
        "…kept an ex's hoodie.", "…returned an ex's stuff dramatically.",
        "…kept a gift from an ex.", "…blocked and unblocked the same person.",
        "…checked an ex's story from a fake account.", "…been the fake account.",
        "…been in a band.", "…played an instrument in public.", "…written a poem for someone.",
        "…written a song about someone.", "…performed at an open mic.",
        "…been booed.", "…been given a standing ovation, even a small one.",
        "…run a race.", "…won a race.", "…finished last and celebrated anyway.",
    ]

    static let neverSpicy: [String] = [
        "…kissed someone in this room.", "…had a one-night stand.", "…done the walk of shame.",
        "…kissed two people in the same night.", "…hooked up with a friend's ex.",
        "…sent a risky text and instantly regretted it.", "…had a crush on someone in this room.",
        "…lied about my body count.", "…hooked up with someone whose name I didn't know.",
        "…been caught kissing where I shouldn't have.", "…skinny-dipped.",
        "…had a friends-with-benefits arrangement.", "…ghosted someone after a date.",
        "…been ghosted after a date.", "…matched with someone in this room on a dating app.",
        "…kissed someone to make somebody else jealous.", "…dated two people at once.",
        "…had a summer fling I still think about.", "…given a fake number.",
        "…slid into a celebrity's DMs.", "…hooked up at a festival.",
        "…had an awkward morning-after breakfast.", "…pretended to be single.",
        "…fallen for a friend.", "…left a party early to meet someone.",
        "…been someone's rebound.", "…kept a hookup secret from this group.",
        "…regretted who I kissed at midnight on New Year's.", "…kissed someone I'd met an hour earlier.",
        "…been kissed and not felt it at all.", "…faked being into a kiss.",
        "…sent a photo I wouldn't want my parents to see.", "…received one I didn't ask for.",
        "…gone through with a dare that involved kissing.", "…kissed a friend on a dare and meant it.",
        "…had a crush on a coworker.", "…flirted to get out of trouble.",
        "…flirted to get a free drink.", "…used a pickup line that actually worked.",
        "…used a pickup line that got me laughed at.", "…had a date end in the first ten minutes.",
        "…had a date end the next morning.", "…been on a date and texted someone else.",
        "…gone on two dates in one day.", "…dated someone my friends hated.",
        "…dated someone I met at a wedding.", "…had a thing with a bartender.",
        "…had a thing with a bouncer.", "…had a thing with a DJ.",
        "…kissed someone in a photo booth.", "…kissed someone in an elevator.",
        "…kissed someone in the sea.", "…kissed someone in the rain, on purpose.",
        "…hooked up in a hotel that wasn't mine.", "…snuck someone into my room.",
        "…snuck out of someone's room.", "…been walked in on.",
        "…walked in on someone.", "…pretended I didn't see anything.",
        "…had a crush confessed to me and panicked.", "…confessed a crush and been rejected.",
        "…confessed a crush and been accepted.", "…written a love letter I never sent.",
        "…received a love letter.", "…had a secret relationship.",
        "…been in a love triangle.", "…been the third person without knowing.",
        "…had an ex reach out on my birthday.", "…reached out to an ex on their birthday.",
        "…texted an ex \"you up?\"", "…received a \"you up?\" text.",
        "…met someone's parents on the first date.", "…lied about how we met.",
        "…hooked up with someone from this group's extended circle.",
        "…had a crush on a friend's partner.", "…kissed a friend's crush.",
        "…been someone's first kiss.", "…had my first kiss at a party.",
        "…kissed someone with braces.", "…kissed someone with a beard and hated it.",
        "…been on a dating app while in a relationship.", "…found my partner on a dating app.",
        "…had a dating profile picture that wasn't me.", "…matched with a coworker.",
        "…matched with a relative by accident.", "…swiped on someone in this room.",
        "…super-liked by accident.", "…been unmatched mid-conversation.",
        "…had a date show up looking nothing like their pictures.",
        "…been told I look nothing like my pictures.", "…faked an emergency to leave a date.",
        "…had a friend call to \"rescue\" me from a date.", "…been the rescue call.",
        "…gotten a tattoo for someone I'm no longer with.", "…stayed over just to avoid a taxi fare.",
        "…gone home with someone and just slept.", "…had breakfast made for me the morning after.",
        "…made breakfast the morning after.", "…had a hookup become a relationship.",
        "…had a relationship become a hookup.", "…said \"I love you\" first.",
        "…said \"I love you\" and not meant it.", "…been said \"I love you\" to too early.",
        "…kissed someone on a dare and then asked for their number.", "…had a crush on a bartender for a whole summer.",
        "…flirted with someone's date at a wedding.", "…been the reason two friends stopped talking.",
        "…hooked up in a tent.", "…hooked up on a boat.", "…hooked up in a car that wasn't moving.",
        "…hooked up in a car that was.", "…kissed someone in a hot tub.", "…kissed someone in a sauna.",
        "…had a secret nickname for a hookup in my phone.", "…saved someone as \"DO NOT ANSWER\".",
        "…answered anyway.", "…gone on a date with two siblings. Not at once.", "…dated a friend's cousin.",
        "…been on a date where I paid and regretted it.", "…been on a date where they paid and I regretted it.",
        "…cried on a date.", "…made someone cry on a date.", "…been on a date that lasted more than 12 hours.",
        "…texted \"I miss you\" to the wrong person.", "…sent a screenshot to the person it was about.",
        "…kept a crush secret for more than a year.", "…had a crush on a friend's parent.",
        "…kissed someone at their own birthday party.", "…kissed the host of a party I crashed.",
        "…hooked up with my neighbour.", "…hooked up with a coworker's ex.", "…had a fling on a school trip.",
        "…been the secret in someone else's relationship.", "…found out I was the secret.",
        "…been dumped for someone in this room.", "…dumped someone for someone in this room.",
        "…faked an orgasm.", "…been sure someone was faking.", "…had a pillow-talk conversation I still think about.",
        "…been asked to leave before breakfast.", "…asked someone to leave before breakfast.",
        "…cooked for someone the morning after and burnt it.", "…left my underwear at someone's place.",
        "…found underwear that wasn't mine.", "…gone home with two people's numbers.", "…lost the number I actually wanted.",
        "…had a crush on my doctor, dentist or PT.", "…kissed someone with a completely different name than I thought.",
        "…had a hookup that started with a bet.", "…kissed a friend while their partner was in the next room.",
        "…been in an open relationship.", "…been asked to be in one and said no.", "…said yes and regretted it.",
        "…kissed a stranger at a festival and never learned their name.", "…had a fling that lasted exactly one weekend.",
        "…texted an ex on New Year's Eve.", "…kissed an ex after they were with someone new.",
        "…met a hookup's parents by accident.", "…been introduced as \"a friend\" when I wasn't.",
        "…introduced someone as \"a friend\" when they weren't.", "…had a relationship nobody in this room knew about.",
        "…been on a first date and slept over.", "…been on a first date and gone home separately at 6 AM.",
        "…kissed someone in this room's ex.", "…had a crush on the same person as someone in this room.",
        "…fought over a crush.", "…lost a friend over a crush.", "…gotten a crush back.",
        "…kissed someone while pretending to be asleep.", "…been kissed while pretending to be asleep.",
        "…snuck out of a window to meet someone.", "…snuck someone in through a window.",
        "…had a hookup interrupted by a parent.", "…had a hookup interrupted by a pet.", "…had a hookup interrupted by a roommate.",
        "…continued anyway.", "…gone to a hotel just for a few hours.", "…booked a hotel in my own city.",
        "…been told I'm a bad kisser.", "…told someone they were a bad kisser.", "…practised kissing on my hand.",
        "…written someone's name on my hand.", "…had someone's name tattooed and covered it.",
        "…had a wedding hookup.", "…had a funeral hookup.", "…had a hookup at a work event.",
        "…kissed a coworker at an office party.", "…dated my boss.", "…been the boss someone dated.",
        "…had my ex show up on a date with someone new.", "…been the someone new.",
        "…gone through with a threesome.", "…been asked and said no.", "…said yes and chickened out.",
        "…kissed someone just to see what it was like.", "…kissed someone of every gender.",
        "…had a same-night rebound.", "…been a same-night rebound.", "…had feelings for a rebound.",
        "…had a friends-with-benefits thing turn into feelings on my side only.", "…on their side only.",
        "…kissed someone who was wearing a costume and didn't know who it was.", "…still don't know.",
    ]

    // MARK: - Pandora's Box

    static let pandoraFree: [String] = [
        "DARE — Swap shirts with the person on your left for the next 3 rounds.",
        "RULE — No first names until your next turn. Slip up = drink.",
        "DARE — Let the group pick your ringtone for the rest of the night.",
        "CHALLENGE — Rock-paper-scissors with the person opposite. Loser drinks 2.",
        "RULE — Only questions until your next turn. Statement = drink.",
        "DARE — Impersonate someone in the group. Wrong guess = they drink.",
        "CHALLENGE — Everyone points at the best dancer on three. Winner hands out 3 drinks.",
        "DARE — Post the 7th photo in your camera roll to your story. Or drink 3.",
        "RULE — Left hand only for drinks until your next turn.",
        "DARE — Speak in an accent of the group's choosing until your next turn.",
        "CHALLENGE — Plank while the group counts to 20. Fail = drink 2.",
        "RULE — Anyone who says \"drink\" drinks. Until your next turn.",
        "DARE — Show the group your most-used emojis.",
        "CHALLENGE — Name 5 cocktails in 10 seconds or drink.",
        "DARE — The person on your right sends one harmless text from your phone.",
        "RULE — Toast before every sip until your next turn.",
        "DARE — Trade seats with whoever the group says has the best laugh.",
        "CHALLENGE — Staring contest with the person opposite. Loser drinks.",
        "DARE — Freestyle rap about the person on your left for 20 seconds.",
        "RULE — The group names you now. Answer only to your new name tonight.",
        "CHALLENGE — Balance your phone on your head for 30 seconds. Drop = drink 2.",
        "DARE — Call your 5th contact and sing one line of ABBA. Or drink 3.",
        "RULE — No pointing until your next turn. Point = drink.",
        "CHALLENGE — The group picks a word. Use it naturally within 2 minutes or drink.",
        "DARE — 10 push-ups or drink 2.",
        "RULE — You're the waiter until your next turn. Fetch everyone's drinks.",
        "DARE — Let the group scroll your camera roll for 10 seconds.",
        "CHALLENGE — Mouth a sentence to the person opposite. They can't guess it = you both drink.",
        "DARE — Dance with no music for 15 seconds while everyone stays silent.",
        "RULE — Compliment everyone you speak to until your next turn.",
        "CHALLENGE — Best story from tonight so far. Group votes; winner hands out 3.",
        "DARE — Talk in third person until your next turn.",
        "CHALLENGE — Eyes closed: name everyone's outfit colours. Each miss = 1 drink.",
        "RULE — The floor is lava when someone shouts it. Last with feet down drinks.",
        "DARE — Recreate your most-used selfie face and hold it for 10 seconds.",
        "CHALLENGE — Thumb war with your pick. Loser drinks 2.",
        "DARE — Give a 30-second TED talk on why your drink is the best.",
        "RULE — Everyone drinks when you drink until your next turn.",
        "CHALLENGE — Say the alphabet backwards. Stumble = drink.",
        "DARE — Do your best runway walk to the bar and back.",
        "RULE — No phones on the table until your next turn. Phone out = drink.",
        "CHALLENGE — Guess how many drinks the group has had tonight. Wrong by 3+ = drink.",
        "DARE — Let the person on your left redo your hair.",
        "RULE — Speak in a whisper until your next turn.",
        "CHALLENGE — Sing the chorus of the last song you played. Group judges.",
        "DARE — Give someone in the group a dramatic slow clap for 15 seconds.",
        "RULE — Everyone must end sentences with \"…allegedly\" until your next turn.",
        "CHALLENGE — Arm wrestle the person opposite. Loser drinks 2.",
        "DARE — Reveal your screen time for today.",
        "RULE — Nobody can say \"yes\" or \"no\" until your next turn.",
        "CHALLENGE — Name 10 countries in 15 seconds or drink.",
        "DARE — Make up a handshake with the person on your right. Perform it.",
        "RULE — Sit on the floor until your next turn.",
        "CHALLENGE — Everyone guesses your phone's lock-screen. Whoever's closest gives out 2.",
        "DARE — Read the last text you sent out loud.",
        "RULE — Only drink with a straw (or pinky up) until your next turn.",
        "CHALLENGE — Do a 20-second impression of a celebrity. Nobody guesses = drink 2.",
        "DARE — Let the group write your next Instagram caption.",
        "RULE — Anyone who laughs at you until your next turn drinks.",
        "CHALLENGE — Don't blink for 20 seconds. Blink = drink.",
        "DARE — Give a heartfelt apology to your drink for neglecting it.",
        "RULE — Everyone must rhyme their next sentence. Fail = drink.",
        "CHALLENGE — Name every person here's middle name. Miss = drink.",
        "DARE — Swap phones with the person opposite for one round. Screen unlocked.",
        "RULE — No swearing until your next turn. Swear = drink.",
        "CHALLENGE — Tell a joke. Nobody laughs = drink 2.",
        "DARE — Give your drink a name and introduce it to the table.",
        "RULE — Everyone speaks like a pirate until your next turn.",
        "CHALLENGE — Recite a full song verse without mistakes.",
        "DARE — Show the group the last photo you took.",
        "RULE — You choose who drinks every time a card says \"drink\" until your next turn.",
        "CHALLENGE — Count backwards from 30 in threes. Mistake = drink.",
        "DARE — Do the worm, or the closest thing to it.",
        "RULE — Nobody can use the word \"like\" until your next turn.",
        "CHALLENGE — Hum a song; first to guess gives out 2 drinks.",
        "DARE — Ask a stranger (or the bartender) for their best joke. Report back.",
        "RULE — Cross your arms every time you talk until your next turn.",
        "CHALLENGE — Everyone holds their breath. First to breathe drinks.",
        "DARE — Let the group pick your drink for the next round.",
        "RULE — Say \"cheers\" in a different language every time you drink.",
        "CHALLENGE — Categories: car brands. Go round; first to stall drinks.",
        "DARE — Do a dramatic death scene. The group rates it.",
        "RULE — You can only laugh with your mouth closed until your next turn.",
        "CHALLENGE — Spell \"Systembolaget\" backwards.",
        "DARE — Do your best impression of your own mother.",
        "RULE — Nobody may touch their hair until your next turn.",
        "CHALLENGE — Categories: things in a bar. Stall = drink.",
        "DARE — Take a selfie with a stranger. Or drink 3.",
        "RULE — Everyone drinks when the DJ changes songs, until your next turn.",
        "CHALLENGE — Wink at the group one by one without smiling.",
        "DARE — Give a weather report for the room.",
        "RULE — Everyone must call you \"boss\" until your next turn.",
        "CHALLENGE — Bar trivia: who's the current Swedish PM? Wrong = drink.",
        "DARE — Sit on someone's lap for the next round.",
        "RULE — Nobody can put their drink down until your next turn.",
        "CHALLENGE — Name 8 ABBA songs in 15 seconds.",
        "DARE — Describe your last dream in full detail.",
        "RULE — Everyone must speak with an accent until your next turn.",
        "CHALLENGE — Drink your next sip with no hands.",
        "DARE — Serenade the person of the group's choosing.",
        "RULE — You must announce every time you drink until your next turn.",
        "CHALLENGE — Pretend to be a news anchor and report tonight's events.",
        "DARE — Reveal your most embarrassing playlist.",
        "RULE — Everyone drinks twice on their next turn.",
        "CHALLENGE — Categories: 90s kids' shows. Stall = drink.",
        "DARE — Act out a movie scene. Group guesses. Nobody? Drink 2.",
        "RULE — Nobody can say the name of the venue until your next turn.",
        "CHALLENGE — Repeat \"Irish wristwatch\" 5 times fast.",
        "DARE — Give the person on your left a dramatic compliment. Make them blush.",
        "RULE — Everyone must sit closer together until your next turn.",
        "CHALLENGE — Do 15 squats. Or drink 3.",
        "DARE — Reveal your browser tabs.",
        "RULE — Nobody may say \"I\" until your next turn.",
        "CHALLENGE — Name every member's hometown. Miss = drink.",
        "DARE — Show the last thing you Googled.",
        "RULE — Everyone drinks when someone checks their phone.",
        "CHALLENGE — Categories: pizza toppings. Stall = drink.",
        "DARE — Do a cartwheel or a handstand attempt.",
        "RULE — You choose a new seating order now.",
        "CHALLENGE — Repeat the last three cards from memory. Miss one = drink.",
        "DARE — Cheers with a stranger.",
        "RULE — Everyone speaks in a robot voice until your next turn.",
        "CHALLENGE — Fold a paper plane. Furthest throw gives out 3.",
        "DARE — Make an animal noise every time you laugh until your next turn.",
        "RULE — Nobody can cross their legs until your next turn.",
        "CHALLENGE — Categories: drinks that start with M. Stall = drink.",
        "DARE — Describe everyone here using only one emoji each.",
        "RULE — The tallest person drinks every time you drink until your next turn.",
        "CHALLENGE — Hold your drink above your head for 30 seconds.",
        "DARE — Do a magic trick. Bad trick = drink.",
        "RULE — Everyone must high-five before they drink until your next turn.",
        "CHALLENGE — Categories: capital cities. Stall = drink.",
        "DARE — Pick someone. Swap drinks for the rest of the round.",
        "RULE — Say \"in my expert opinion\" before every sentence until your next turn.",
        "CHALLENGE — Tongue twister: \"Sju sjösjuka sjömän.\" Three times fast.",
        "DARE — Show your most recent meme.",
        "RULE — Everyone drinks when someone says a name until your next turn.",
        "CHALLENGE — Name 6 Swedish cities in 10 seconds.",
        "DARE — Reveal the last thing you bought online.",
        "RULE — Give out 3 drinks however you like right now.",
        "CHALLENGE — Guess the age of a stranger the group picks. Wrong by 5+ = drink.",
        "DARE — Do a dramatic reading of your last voice message.",
        "RULE — Nobody can say \"drink\", \"drunk\" or \"drinking\" until your next turn.",
        "CHALLENGE — Do a shot of water. Yes, water. Hydrate, hero.",
        "DARE — Do a stand-up bit about the group. 30 seconds.",
        "RULE — Everyone drinks when you blink for the next 30 seconds.",
        "CHALLENGE — Categories: things you'd find in a hangover kit.",
        "DARE — Give the group a fashion critique. Be brutal.",
        "RULE — Everyone must speak in a question voice? Until your next turn?",
        "CHALLENGE — Categories: euro-pop artists. Stall = drink.",
        "DARE — Tell the table your most embarrassing nickname.",
        "RULE — Nobody can drink until they've told a fun fact.",
        "CHALLENGE — Everyone guesses your bank balance direction: up or down since last month. Loser drinks.",
        "DARE — Do a dramatic slow-motion walk to the bathroom and back.",
        "RULE — Everyone drinks with their eyes closed until your next turn.",
        "CHALLENGE — Pull your best surprised face. Group votes; worst drinks.",
        "DARE — Write a haiku about the person opposite. Perform it.",
        "RULE — You decide: everyone drinks now, or nobody drinks for 3 cards.",
        "CHALLENGE — Categories: things in a wallet. Stall = drink.",
        "DARE — Pick a song. Everyone dances for 15 seconds or drinks.",
        "RULE — Nobody may laugh until your next turn. Laugh = drink.",
        "CHALLENGE — Recreate a famous painting with your body. Group guesses.",
        "DARE — Post a story that says \"I lost a bet\" — no context.",
        "RULE — Everyone drinks when the bar plays a song from before 2010.",
        "CHALLENGE — Name 5 things you love about the person on your right. In 15 seconds.",
        "DARE — Ask the bartender to pick your next drink.",
        "RULE — Everyone must fist-bump you before drinking until your next turn.",
        "CHALLENGE — Categories: Swedish snacks. Stall = drink.",
        "DARE — Explain how to make your favourite cocktail like a chemistry teacher.",
        "RULE — Nobody may say \"literally\" until your next turn.",
        "CHALLENGE — Order everyone by birthday in 30 seconds. Wrong = you drink.",
        "DARE — Do a lip-sync of the current song. Full commitment.",
        "RULE — Everyone drinks whenever you drink for the rest of the round.",
        "CHALLENGE — Count how many people are wearing black. Wrong = drink.",
        "DARE — Show the group your Spotify Wrapped or top artist.",
        "RULE — Nobody can lean back until your next turn.",
        "CHALLENGE — Categories: movie villains. Stall = drink.",
        "DARE — Adopt a signature pose for every photo tonight.",
        "RULE — Everyone must clink glasses with everyone before drinking, until your next turn.",
        "CHALLENGE — Be a mime for one whole round.",
        "DARE — Reveal your phone battery. Under 20% = drink 2.",
        "RULE — Everyone drinks when someone leaves the table until your next turn.",
        "CHALLENGE — Name 10 drinks in 15 seconds.",
        "DARE — Invent a new dance move and teach it to the table.",
    ]

    static let pandoraSpicy: [String] = [
        "DARE — Give someone of your choice a 10-second shoulder massage.",
        "TRUTH — Your worst date in 3 sentences. Refuse = drink 3.",
        "DARE — Whisper something flirty to the person on your right. They rate it; under 5, you drink.",
        "RULE — You and the person opposite are \"married\" until your next turn: you drink when they drink.",
        "TRUTH — Desert island with this group: who do you keep, who's voted off first?",
        "DARE — Let the group read your last DM out loud. Or drink 4.",
        "TRUTH — Show your dating profile. No profile? Everyone else drinks.",
        "DARE — Serenade the person of your choice with 15 seconds of a love song.",
        "TRUTH — Most embarrassing hookup story, one-sentence version allowed.",
        "DARE — Your sexiest dance move. Group rates it; under 5 = drink 2.",
        "RULE — Eye contact with whoever you talk to. Look away = sip. Until your next turn.",
        "TRUTH — First impression of everyone here, rapid-fire honest.",
        "DARE — Let someone set your dating app bio for a week. Or drink 3.",
        "TRUTH — Ever had a crush on someone in this group? Yes or no is enough.",
        "DARE — Recreate a romcom kiss scene with your own hand. Full commitment.",
        "TRUTH — Boldest text you've ever sent. Paraphrasing allowed.",
        "DARE — Pick someone. 20 seconds of eye contact without laughing. Loser drinks.",
        "TRUTH — Your green flag, and the red flag you refuse to fix.",
        "DARE — Best pickup line on the person opposite. Smile = they drink; no smile = you do.",
        "TRUTH — Ever faked liking a song, hobby or food to impress someone? Story.",
        "DARE — Text your crush \"thinking about you\". Or drink 4.",
        "TRUTH — Describe your type. Group guesses whether your ex matched.",
        "DARE — Slow dance with the person of your choice. 15 seconds. No music.",
        "TRUTH — Wildest night out of your life, short version, no skipping the good part.",
        "DARE — Sit on the lap of the person the group chooses for one round.",
        "TRUTH — Who was your last kiss? First name only. Refuse = drink 3.",
        "DARE — Let the group send one flirty emoji to a contact of their choice.",
        "TRUTH — Have you ever kissed anyone in this room? Yes/no.",
        "DARE — Give the person on your left a hickey-free neck kiss on the cheek. Or drink 2.",
        "TRUTH — Your most-used excuse to leave someone's place in the morning.",
        "DARE — Reveal your phone's search history from last Saturday.",
        "TRUTH — Rate your own kissing out of 10. Group adjusts it.",
        "DARE — Bite your lip and hold eye contact with the person opposite for 10 seconds.",
        "TRUTH — What's the most embarrassing thing you've said during a date?",
        "DARE — Let the group choose a contact. Send them \"we need to talk.\" Or drink 4.",
        "TRUTH — Ever dated two people at once? Details optional.",
        "DARE — Feed the person on your right a snack or a sip. Romantically.",
        "TRUTH — Your celebrity hall pass. Group decides if it's realistic.",
        "DARE — Do a 10-second lap-dance move on the nearest chair. Not a person.",
        "TRUTH — The longest you've gone without kissing anyone.",
        "DARE — Show the last person you texted after midnight.",
        "TRUTH — Ever ghosted someone in this room's circle? Confess.",
        "DARE — Reenact your first kiss with a pillow, bottle, or your own arm.",
        "TRUTH — Ever pretended to be single? Why?",
        "DARE — Compliment the person opposite's body, tastefully, for 15 seconds.",
        "TRUTH — What's your biggest turn-off? The group guesses first; wrong guesses drink.",
        "DARE — Let the person on your left take a \"thirst trap\" photo of you.",
        "TRUTH — Ever kissed someone to get out of a conversation?",
        "DARE — Blow a kiss to a stranger. Or drink 3.",
        "TRUTH — What did you do the morning after your last hookup?",
        "DARE — Trade an item of clothing with the person the group picks.",
        "TRUTH — Have you ever sent a photo you'd delete today?",
        "DARE — Describe your ideal date night in a seductive voice.",
        "TRUTH — Ever had a crush on a friend's partner? Yes/no.",
        "DARE — Let the group swipe on your dating app for 60 seconds.",
        "TRUTH — Ever cried after a hookup? Story optional.",
        "DARE — Your best \"come hither\" look at the person of the group's choosing.",
        "TRUTH — Who here would you take to a wedding as a plus one?",
        "DARE — Give a foot massage to the person on your right for 20 seconds. Or drink 3.",
        "TRUTH — Ever matched with someone and realised you knew them? How did it end?",
        "DARE — Read your last three notifications aloud.",
        "TRUTH — What's your most-used pickup line? Prove it works on the person opposite.",
        "DARE — Do a striptease with a jacket only. Full jacket. Nothing else.",
        "TRUTH — Ever kissed someone and immediately regretted it? Why?",
        "DARE — Hold hands with the person opposite until your next turn.",
        "TRUTH — Rate the group's flirting skills, best to worst.",
        "DARE — Whisper the name of your crush into the ear of the person on your left.",
        "TRUTH — Ever had a summer romance? What ended it?",
        "DARE — Post a story with the caption \"single and ready\" — or \"taken and thriving\" — group picks.",
        "TRUTH — Ever fallen asleep during a date? Or on one?",
        "DARE — Pick someone. Write them a two-line love poem. Now.",
        "TRUTH — What's your dating deal-breaker that others say is unfair?",
        "DARE — Do your best seductive voice reading the bar menu.",
        "TRUTH — Ever pretended to lose someone's number?",
        "DARE — Let the group pick the next person you match with.",
        "TRUTH — Best kiss of your life: where and roughly when.",
        "DARE — Pinky-swear with someone to go on a date within a month. Or drink 4.",
        "TRUTH — What would your ex say your worst habit was?",
        "DARE — Blindfolded (hands over eyes), guess who's touching your hand.",
        "TRUTH — Ever lied about your age on a date?",
        "DARE — Give the person opposite a nickname based on their flirting style.",
        "TRUTH — Ever hooked up with a coworker or classmate?",
        "DARE — Trade phones with the person on your right for one round. Both unlocked.",
        "TRUTH — Ever used a friend as a fake partner?",
        "DARE — Look the person on your left in the eye and say \"you're the one\" without laughing.",
        "TRUTH — Your most awkward first kiss moment.",
        "DARE — Give the group a tour of your camera roll from the last night out.",
        "TRUTH — Ever gone on a date with someone way older or younger?",
        "DARE — Say what you find attractive about everyone here. In 30 seconds.",
        "TRUTH — Ever stayed in a relationship just to avoid being single?",
        "DARE — Let the person opposite pick a contact. Send them your best selfie with no caption. Or drink 3.",
        "TRUTH — Which two people in this room would make the best couple? Say it to their faces.",
        "DARE — Give the person on your right a nickname you'd use in bed. Say it with a straight face.",
        "TRUTH — What's the longest you've kept a hookup going without telling anyone?",
        "DARE — Reenact the last time you got rejected. The group plays the rejecter.",
        "TRUTH — What's the worst thing you've done to get out of a date?",
        "DARE — Recite your dating app bio in a movie-trailer voice.",
        "TRUTH — Have you ever gone on a date with someone in this room? Yes/no is enough.",
        "DARE — Put your head on the shoulder of the person on your left until your next turn.",
        "TRUTH — Which friend's ex would you date? Names or drink 3.",
        "DARE — Send a voice note saying \"I miss you\" to the contact the group picks. Or drink 4.",
        "RULE — Until your next turn, everyone must speak to you in a flirty voice. Break = drink.",
        "TRUTH — What do you do differently on a date you actually care about?",
        "DARE — Make eye contact with the person opposite and describe their eyes for 20 seconds.",
        "TRUTH — What's your number? Round it if you must. Refuse = drink 4.",
        "DARE — Sit back-to-back with someone. Guess how many drinks they've had; they guess yours. Loser drinks.",
        "TRUTH — Your most-used excuse to not go home with someone.",
        "DARE — Pretend to propose to the person on your right. Full speech. Ring optional.",
        "TRUTH — What's the most embarrassing thing in your camera roll? Describe, don't show.",
        "DARE — Now show it. Or drink 4.",
        "RULE — Nobody may say the word \"ex\" until your next turn. Say it = drink.",
        "TRUTH — Have you ever been someone's secret? How long?",
        "DARE — Give a two-line toast to your most memorable kiss.",
        "TRUTH — Which of your friends' partners do you secretly rate?",
        "DARE — Let the group set your phone wallpaper to a photo of someone here for the night.",
        "TRUTH — Ever had a crush on someone twice your age? Or half?",
        "DARE — Dance with the person opposite for 20 seconds. The group picks the song by humming.",
        "TRUTH — Describe your last kiss in three words.",
        "DARE — Tell the person on your left one thing you'd change about their flirting.",
        "TRUTH — Have you ever lied about being on a date to get out of plans with this group?",
        "DARE — Kiss the back of your own hand like it's someone you're into. 10 seconds. Commit.",
        "TRUTH — What's the boldest thing anyone's ever said to you? Repeat it.",
        "DARE — Draw a heart on the person on your right with your finger. On their face.",
        "TRUTH — Ever kissed someone in this room's family? Yes/no.",
        "DARE — Give a 15-second review of your first kiss like a food critic.",
        "TRUTH — Who in this group texts you the latest at night?",
        "DARE — Swap seats so you're next to the person the group thinks you fancy.",
        "TRUTH — What's the strangest place you've been kissed?",
        "DARE — Whisper a compliment to everyone here. One by one. Make it good.",
        "RULE — Until your next turn, every sip must be followed by a wink at someone.",
        "TRUTH — Which dating app have you spent the most time on, honestly?",
        "DARE — Reveal your last three dating app matches by first name.",
        "TRUTH — Have you ever gone back to someone you swore was over?",
        "DARE — Give the person opposite a lap dance… from two metres away. Interpret freely.",
        "TRUTH — Your biggest romantic regret. One sentence.",
        "DARE — Call your most recent crush on speaker and say one sentence. Or drink 5.",
        "TRUTH — Who's the best kisser you know? They can be here.",
        "DARE — Let the person on your right fix your hair \"for a date\". No mirror until your next turn.",
        "TRUTH — What's the most attractive thing someone can do at a bar?",
        "DARE — Do the most attractive thing someone can do at a bar. Now.",
        "TRUTH — Ever faked a phone call to avoid someone you'd kissed?",
        "DARE — Take a couple photo with the person of the group's choosing. Post it or drink 3.",
        "TRUTH — Which of your exes would your parents want you back with?",
        "DARE — Give everyone here a compatibility score out of 10 with you.",
        "TRUTH — When did you last check an ex's profile? Be honest.",
        "DARE — Trade a secret with the person opposite. Whispered. Then both drink.",
        "TRUTH — What's the pettiest reason you've rejected someone?",
        "DARE — Blow-dry the person on your left with your breath for 10 seconds. Yes.",
        "TRUTH — Have you ever gotten back with someone just for the afterparty?",
        "DARE — Read the last flirty message you sent. Voice acting required.",
        "TRUTH — Ever been in love with two people at once?",
        "DARE — Give the person on your right a shoulder-to-shoulder slow lean for one full song.",
        "TRUTH — What's your go-to move when you like someone at a party?",
        "DARE — Do the move on the person the group picks.",
        "TRUTH — Which of your friends would you set up with the person opposite?",
        "DARE — Sing \"Dancing Queen\" to someone as if it's a love song. One verse.",
        "TRUTH — Ever kept a date secret from this group? Why?",
        "DARE — Hold the gaze of the person opposite for 30 seconds. First to look away drinks 2.",
        "TRUTH — Rate tonight's outfits for date potential. Best and worst.",
        "DARE — Ask the bartender or a stranger for dating advice. Report back.",
        "TRUTH — Ever been the reason someone broke up?",
        "DARE — Let the person on your left text your last match. One message.",
        "TRUTH — What would your last hookup say about you in one sentence?",
        "DARE — Give the person opposite a dramatic movie-style hug. 10 seconds.",
        "TRUTH — Which song makes you think of someone here?",
        "DARE — Do a 10-second runway walk that ends with a wink at the group's pick.",
        "TRUTH — Ever pretended to like someone's friend to get closer to them?",
        "DARE — Tell everyone one thing you find attractive that most people don't.",
        "TRUTH — How many people have you kissed this year? Round up.",
        "DARE — Remove one accessory or layer and hand it to the person the group picks until your next turn.",
        "TRUTH — What's the biggest lie you've told on a date?",
        "DARE — Give the person on your right a five-second forehead kiss. Or drink 3.",
        "TRUTH — Which movie kiss would you recreate, and with who here?",
        "DARE — Recreate it. Air-kiss version allowed.",
        "TRUTH — Ever been on a date and run into an ex? What happened?",
        "DARE — Do your best seductive eyebrow raise at everyone here in turn.",
        "TRUTH — What's the one thing you'd never tell a partner?",
        "DARE — Sit on the floor at the feet of the person the group picks until your next turn.",
        "TRUTH — Ever faked an interest to get a second date? What was it?",
        "DARE — Let the group vote on your dating red flag. Accept it out loud.",
        "TRUTH — Which of these would you rather: your search history or your DMs read aloud?",
        "DARE — Do a slow-motion hair flip toward the person opposite.",
        "TRUTH — Have you ever dated someone for their apartment, car or connections?",
        "DARE — Compliment yourself in the mirror of your phone for 15 seconds. Out loud.",
        "TRUTH — Who was the last person you thought about before falling asleep?",
        "DARE — Give the person the group picks a piggyback to the bar and back. Or drink 3.",
        "TRUTH — What's the most romantic thing you've done that failed completely?",
        "DARE — Pretend the person on your left just dumped you. React for 20 seconds.",
        "TRUTH — Ever lied about your relationship status on a night out?",
        "DARE — Give the person opposite a 10-second hand massage. Eye contact the whole time.",
        "TRUTH — What's your kissing style in one word? The group gets to correct it.",
        "DARE — Create a couple name with the person the group picks. Announce it to the bar.",
        "TRUTH — Ever ghosted someone who's now in this room's circle?",
        "DARE — Do a 20-second interpretive dance about your love life.",
        "TRUTH — What's the fastest you've ever fallen for someone?",
        "DARE — Post \"taken\" or \"single\" on your story — the group decides which.",
        "TRUTH — Who's had the most influence on your type? They might be here.",
    ]

    // MARK: - Most Likely To

    static let mostLikelyFree: [String] = [
        "…become famous.", "…end tonight with a kebab.", "…cry during a Disney movie.",
        "…lose their phone tonight.", "…start the dance floor.", "…talk their way out of a fine.",
        "…befriend the bouncer.", "…be a millionaire by 35.", "…move abroad on a whim.",
        "…laugh at the wrong moment.", "…fall asleep first tonight.",
        "…order the most expensive thing on the menu.", "…survive a zombie apocalypse.",
        "…become a politician.", "…like a 2014 photo while stalking.",
        "…know every lyric tonight.", "…start a business with no plan.", "…win a reality show.",
        "…get lost on the way home.", "…adopt five dogs.", "…send a voice message over 3 minutes.",
        "…be late to their own wedding.", "…eat someone's fries without asking.",
        "…become everyone's boss one day.", "…book a flight during this game.",
        "…have an embarrassing search history.", "…fight for the aux cable.", "…start a podcast.",
        "…get a tattoo they regret.", "…charm their way backstage.", "…still be partying at 60.",
        "…trip walking into the club.", "…text the group chat at 4 AM.", "…become a meme.",
        "…give a toast that goes on too long.", "…bring a stranger to the afterparty.",
        "…forget where they parked.", "…win a pub quiz single-handedly.", "…lose a pub quiz single-handedly.",
        "…accidentally call their boss at 2 AM.", "…own a boat one day.", "…live on a boat one day.",
        "…get kicked out of a museum.", "…cry at a concert.", "…sing louder than the artist at a concert.",
        "…spend their whole paycheck in one weekend.", "…retire at 40.", "…never retire.",
        "…run a marathon.", "…quit a marathon at 5 km.", "…forget their own birthday.",
        "…throw the best birthday party.", "…show up to a costume party in normal clothes.",
        "…overdo the costume.", "…become a teacher.", "…get fired for being too honest.",
        "…get promoted for being too charming.", "…start a fight with a vending machine.",
        "…hug a stranger tonight.", "…be on a billboard.", "…write a book.",
        "…read a whole book in a night.", "…win the lottery and lose the ticket.",
        "…give away their lottery winnings.", "…forget someone's name mid-introduction.",
        "…have the messiest room.", "…have the cleanest room.", "…cook for the whole group.",
        "…burn water.", "…order pizza to the club.", "…go vegan for a week and quit.",
        "…be in a band.", "…be a roadie for a band.", "…cry at their own wedding.",
        "…object at someone else's wedding.", "…become a wedding DJ.", "…become a therapist.",
        "…need a therapist after tonight.", "…get a pet snake.", "…get a pet pig.",
        "…move back in with their parents.", "…buy a house first.", "…win an argument with a GPS.",
        "…take the stairs to avoid small talk in the lift.", "…make friends in the lift.",
        "…still use the same password from 2012.", "…get hacked.", "…be a spy.",
        "…be caught being a spy in five minutes.", "…live to 100.", "…skydive.",
        "…faint before skydiving.", "…host a dinner party.", "…arrive at the dinner party empty-handed.",
        "…leave a party without saying goodbye.", "…be the last one at every party.",
        "…lose a bet and pay double.", "…win a bet and forget to collect.",
        "…own a restaurant.", "…get banned from a restaurant.", "…become a food critic.",
        "…eat the same meal every day.", "…discover a new species.", "…become a species.",
        "…run for mayor.", "…get elected by accident.", "…have a secret talent nobody knows.",
        "…have no secret talents but claim five.", "…rescue a cat from a tree.", "…be rescued from a tree.",
        "…join a cult by accident.", "…start a cult by accident.", "…become a monk for a year.",
        "…own 50 plants.", "…kill 50 plants.", "…marry a celebrity.", "…be mistaken for a celebrity.",
        "…be the group's designated driver forever.", "…miss their own surprise party.",
        "…plan the best surprise party.", "…forget to invite the guest of honour.",
        "…lose their keys tonight.", "…find someone else's keys tonight.", "…win a karaoke contest.",
        "…get booed at karaoke.", "…stay friends with every ex.", "…block every ex.",
        "…become a morning person.", "…never see a sunrise sober.", "…go viral for the wrong reason.",
        "…go viral for the right reason.", "…become an influencer.", "…unfollow everyone on a whim.",
        "…quit social media and come back in a week.", "…have 10,000 unread emails.",
        "…have inbox zero.", "…forget to reply for a month.", "…reply within 3 seconds, always.",
        "…win a dance-off.", "…injure themselves in a dance-off.", "…get a sports scholarship.",
        "…get a scholarship for arguing.", "…become a lawyer.", "…need a lawyer.",
        "…be a game-show contestant.", "…be a game-show host.", "…fall for a scam.",
        "…run a scam (a legal one).", "…adopt a highway.", "…get lost on a highway.",
        "…build a treehouse as an adult.", "…live in the treehouse.", "…become a stand-up comedian.",
        "…be heckled at stand-up.", "…take a gap year that becomes five.", "…finish a degree in record time.",
        "…win an Oscar.", "…thank their dog in the Oscar speech.", "…become an astronaut.",
        "…get lost in space.", "…start a farm.", "…get chased by a goose on the farm.",
        "…become a pro gamer.", "…rage-quit Monopoly.", "…flip the Monopoly board.",
        "…solve a Rubik's cube.", "…peel the stickers off a Rubik's cube.", "…win a hot-dog eating contest.",
        "…enter a hot-dog eating contest by mistake.", "…climb a mountain.", "…take the cable car and say they climbed.",
        "…become a pilot.", "…be terrified of flying.", "…sleep through an earthquake.",
        "…sleep through their alarm today.", "…invent something useful.", "…invent something useless and sell it.",
        "…become a chef.", "…set off the smoke alarm making toast.", "…be a hermit.",
        "…know everyone in the city.", "…become a professional cuddler.", "…hate hugs.",
    ]

    static let mostLikelySpicy: [String] = [
        "…kiss a stranger tonight.", "…have the wildest dating app stories.",
        "…date two people at once and get away with it.", "…fall in love on vacation.",
        "…send a risky text tonight.", "…have a secret admirer in this room.",
        "…leave the party with someone's number.", "…get back with their ex.",
        "…have a celebrity hall pass they'd actually use.", "…flirt with the bartender for free drinks.",
        "…have kissed someone in this group.", "…plan a wedding on the second date.",
        "…ghost someone by accident.", "…have their read receipts on, on purpose.",
        "…fake a phone call to escape a bad date.", "…say \"I love you\" first.",
        "…have a type everyone can describe.", "…marry rich.", "…cause the drama on a dating show.",
        "…slide into a DM tonight.", "…have the best kiss-and-tell story.",
        "…be someone's ex they still think about.", "…turn a one-night stand into a relationship.",
        "…know exactly what their ex is doing right now.", "…kiss two people in one night.",
        "…have a crush on someone here right now.", "…be on a dating app right now, under the table.",
        "…match with someone here if they were on the app.", "…have a hookup they've told nobody about.",
        "…hook up with a friend's ex.", "…forgive a friend for hooking up with their ex.",
        "…never forgive it.", "…go on a date with someone twice their age.",
        "…be a serial monogamist.", "…never settle down.", "…get married in Vegas.",
        "…get married in Vegas and stay married.", "…have a holiday romance every summer.",
        "…keep a hoodie from every ex.", "…burn everything an ex ever gave them.",
        "…cry over an ex in the bathroom tonight.", "…text an ex tonight.",
        "…be the reason someone deletes a dating app.", "…be the reason someone downloads one.",
        "…get a tattoo of a partner's name.", "…get it covered within a year.",
        "…date a coworker.", "…date the boss.", "…be the one who \"doesn't do labels\".",
        "…ask \"what are we?\" on the first date.", "…fall for their best friend.",
        "…be the best friend everyone falls for.", "…have the most exes in this room.",
        "…have the fewest exes and the best stories.", "…kiss someone at midnight on New Year's.",
        "…kiss the wrong person at midnight.", "…have a fling with a DJ.",
        "…have a fling with a bartender.", "…have a fling with a tourist.",
        "…be the tourist someone has a fling with.", "…get caught sneaking out.",
        "…get caught sneaking someone in.", "…leave a date through a bathroom window.",
        "…go on a date and end up at their parents' place.", "…meet the parents in week one.",
        "…never meet the parents.", "…be the one with the hidden dating app folder.",
        "…post a couple photo within 24 hours of a first date.", "…soft-launch a partner and never hard-launch.",
        "…hard-launch and break up the next week.", "…be the friend that plans everyone's dates.",
        "…be the friend everyone calls after a date.", "…have the worst taste in partners.",
        "…have the best taste and still pick wrong.", "…kiss someone with a bad breath excuse.",
        "…fall asleep on a first date.", "…propose on a first date.", "…say yes to that proposal.",
        "…date someone from this room's friend group.", "…have already dated someone from it.",
        "…flirt with everyone and mean none of it.", "…flirt with no one and mean all of it.",
        "…be the group's love guru.", "…need the group's love guru.", "…have a secret couple's playlist.",
        "…have a breakup playlist longer than the couple's one.", "…cry in a club bathroom over love.",
        "…leave a club with a new love.", "…be the person exes warn each other about.",
        "…be the ex everyone stays friends with.", "…have a crush on a friend's sibling.",
        "…have a crush on a sibling's friend.", "…kiss someone in this room before the night ends.",
        "…already have.", "…lie about it.",
        "…have a hookup in their contacts under a fake name.", "…get a number from the bar staff tonight.",
        "…kiss their ex at a wedding.", "…be the ex that gets kissed at a wedding.",
        "…date someone just for the free dinners.", "…be dated for their free dinners.",
        "…have a secret second dating app.", "…have matched with a coworker and hidden it.",
        "…wake up in a different city after a date.", "…propose after three months.",
        "…say yes after three months.", "…have a wedding with an open bar and no food.",
        "…turn a work trip into a romance.", "…fall for the tour guide.", "…fall for the flight attendant.",
        "…have a holiday fling that follows them home.", "…get caught sneaking out of a hotel.",
        "…lose a bet and have to go on a blind date.", "…set up a blind date for someone here.",
        "…be single by choice for a decade.", "…never be single for more than a week.",
        "…be a bad texter but a great kisser.", "…be a great texter but a terrible kisser.",
        "…have a crush confessed to them tonight.", "…confess a crush tonight.",
        "…date a celebrity lookalike and pretend it's the real thing.", "…get a matching tattoo on a first date.",
        "…be in a relationship they haven't told this group about.", "…have a partner who's never met this group.",
        "…have the wildest bachelor or bachelorette party.", "…get thrown out of a bachelor or bachelorette party.",
        "…kiss someone with the same name as their ex.", "…call someone the wrong name in bed.",
        "…be called the wrong name and laugh about it.", "…have a hookup that turns into a roommate.",
        "…have a roommate that turns into a hookup.", "…date a friend's sibling and make it work.",
        "…be the group's most eligible single.", "…be the group's least eligible single and not know it.",
        "…be the person who says \"we're just friends\" the most.", "…actually be just friends.",
        "…keep an ex's number \"just in case\".", "…use the number.", "…have a wedding playlist ready and no partner.",
        "…book a couples' spa day alone.", "…get a couple's discount by faking it.",
        "…have a summer with three flings.", "…have a summer with zero flings and the best stories anyway.",
        "…kiss the DJ.", "…be kissed by the DJ.", "…have a song written about them.", "…write a song about someone here.",
        "…have their ex's new partner on their story views.", "…be on their ex's new partner's story views.",
        "…cry at a stranger's wedding.", "…kiss a stranger at a stranger's wedding.",
        "…go to a couples' therapist on a second date.", "…break up on a holiday.", "…get together on a holiday.",
        "…get engaged in a bar bathroom.", "…say the L-word on a dance floor.", "…mean it.",
        "…have a hall pass list longer than five.", "…have never thought about a hall pass and lie about it.",
        "…date their personal trainer.", "…date their barber or hairdresser.", "…date the bouncer.",
        "…get a free drink with a wink.", "…try and get a bill instead.", "…be the group's designated flirt.",
        "…be the group's designated \"we're leaving now\" voice.", "…have the most read-and-ignored messages.",
        "…reply to a crush in under ten seconds and pretend they didn't.", "…date a twin and get confused.",
        "…have a thing with someone whose name they can't spell.", "…be the reason someone learns their name.",
        "…leave a party early for a booty call.", "…pretend it's an early meeting.", "…be caught.",
        "…have a fling with an ex's friend.", "…have a fling with a friend's ex's friend.",
        "…make out on public transport.", "…get told off for making out on public transport.",
        "…kiss someone in the rain on purpose.", "…kiss someone in the snow and regret the cold.",
        "…kiss someone at sunrise after a night out.", "…still be kissing them at noon.",
        "…have a hookup that becomes a group chat legend.", "…be the group chat legend and deny it.",
        "…get back with an ex three times.", "…get back with an ex three times tonight.",
        "…have a crush on someone here's partner.", "…know exactly who that is right now.",
        "…meet their soulmate at a bar.", "…meet their soulmate and not notice.",
        "…take a stranger home tonight.", "…be the stranger someone takes home tonight.",
        "…make the first move tonight.", "…wait forever for someone else to make it.",
    ]
}
